-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnf4hQPaZUKQ2Jrr9
JFMLip4xzrRRk3PbhZbbl31LgfugCgYIKoZIzj0DAQehRANCAATHTLosmqAzvbFk
nQxO4VmBwCwmKDWGZMTtKPM26SQ+Jr+Dl3JJF8cAGq2lmlbr705HKOpKkWuILiz1
Qo2Np3E4
-----END PRIVATE KEY-----